version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
      - ./data/influx:/var/lib/influxdb
  chronograf:
    image: chronograf:latest
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb
  grafana:
    image: grafana/grafana:6.2.5
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
