.PHONY: clean All

All:
	@echo "----------Building project:[ bmCoordinator - Debug ]----------"
	@cd "bmCoordinator" && "$(MAKE)" -f  "bmCoordinator.mk"
clean:
	@echo "----------Cleaning project:[ bmCoordinator - Debug ]----------"
	@cd "bmCoordinator" && "$(MAKE)" -f  "bmCoordinator.mk" clean
