.PHONY: clean All

All:
	@echo "----------Building project:[ rp_datalogger - Debug ]----------"
	@cd "rp_datalogger" && "$(MAKE)" -f  "rp_datalogger.mk"
clean:
	@echo "----------Cleaning project:[ rp_datalogger - Debug ]----------"
	@cd "rp_datalogger" && "$(MAKE)" -f  "rp_datalogger.mk" clean
