function [] = fbf_PrintTextTable( data )
%FBF_PRINTTEXTTABLE FogBenchmarkFramework LatexTable
%   prints the data generated by fbf_GetData();

max = size(data,2);

begin='\begin{tabular}{ | c';
title='';
memAvg='MemAvg(KB)';
maxMem='MemMax(KB)';
cpuAvg='CpuAvg(\%)';
maxCpu='CpuMax(\%)';
outAvg='Out(KB)';
inAvg='In(KB)';
preCurrentAvg='Pre:(mA)';
runCurrentAvg='Run:(mA)';
energyAvg='Energy(Jouls)';
mAmpsSAvg='Energy(mAs)';
mAmpsHAvg='Energy(mAh)';
time='Time(ms)';


for i = 1 : max
    begin=sprintf("%s | c",begin);
    title=sprintf("%s&%s-%s-%s",title,data(i).platform, data(i).lang, data(i).protocol); 
    memAvg=sprintf("%s& %f",memAvg,data(i).memAvg);
    maxMem=sprintf("%s& %f",maxMem,data(i).maxMem);
    cpuAvg=sprintf("%s& %f",cpuAvg,data(i).cpuAvg);
    maxCpu=sprintf("%s& %f",maxCpu,data(i).maxCpu);
    outAvg=sprintf("%s& %f",outAvg,data(i).outAvg);
    inAvg=sprintf("%s& %f",inAvg,data(i).inAvg);
    preCurrentAvg=sprintf("%s& %f",preCurrentAvg,data(i).preCurrentAvg);
    runCurrentAvg=sprintf("%s& %f",runCurrentAvg,data(i).runCurrentAvg);
    energyAvg=sprintf("%s& %f",energyAvg,data(i).energyAvg);
    mAmpsSAvg=sprintf("%s& %f",mAmpsSAvg,data(i).mAmpsSAvg);
    mAmpsHAvg=sprintf("%s& %f",mAmpsHAvg,data(i).mAmpsSAvg/3600);
    time=sprintf("%s& %f",time,data(i).time);
end
fprintf("%s | } \n \\hline  \n",begin);
fprintf("  %s \\\\ \\hline \n",title);
fprintf("  %s \\\\ \\hline \n",memAvg);
fprintf("  %s \\\\ \\hline \n",maxMem);
fprintf("  %s \\\\ \\hline \n",cpuAvg);
fprintf("  %s \\\\ \\hline \n",cpuAvg);
fprintf("  %s \\\\ \\hline \n",maxCpu);
fprintf("  %s \\\\ \\hline \n",outAvg);
fprintf("  %s \\\\ \\hline \n",inAvg);
fprintf("  %s \\\\ \\hline \n",preCurrentAvg);
fprintf("  %s \\\\ \\hline \n",runCurrentAvg);
fprintf("  %s \\\\ \\hline \n",energyAvg);
fprintf("  %s \\\\ \\hline \n",mAmpsSAvg);
fprintf("  %s \\\\ \\hline \n",mAmpsHAvg);
fprintf("  %s \\\\ \\hline \n",time);
fprintf("\\end{tabular}\n");
end

