function [] = fbf_PrintData( data )
%FBF_PRINTDATA FogBenchmarkFramework Print Data
%   prints the data generated by fbf_GetData();

fprintf("%s-%s-%s stats:\n",data.platform, data.lang, data.protocol);
fprintf("\tMemAvg: %f KB\n",data.memAvg);
fprintf("\tMemMax: %f KB\n",data.maxMem);
fprintf("\tCpuAvg: %f %%\n",data.cpuAvg);
fprintf("\tCpuMax: %f %%\n",data.maxCpu);
fprintf("\tOut: %f KB\n",data.outAvg);
fprintf("\tIn: %f KB\n",data.inAvg);
fprintf("\tPre: %f mAmps\n",data.preCurrentAvg);
fprintf("\tRun: %f mAmps\n",data.runCurrentAvg);
fprintf("\tEnergy: %f Jouls\n",data.energyAvg);
fprintf("\tEnergy: %f mAs\n",data.mAmpsSAvg);
fprintf("\tEnergy: %f mAh\n",data.mAmpsSAvg/3600);
fprintf("\tTime: %i ms\n",data.time);
fprintf("\tCycle Time: %f ms\n",data.cycleTime);
fprintf("\tPower Estimation: %f mAh\n",data.powerEstimation);
end

