apiVersion: v1
kind: Namespace
metadata:
  name: bm-fw
  labels:
    app: bm-fw
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: bm-fw
  labels:
    app: bm-fw
subsets:
  - addresses:
    - ip: 192.168.1.10
    - ip: 192.168.1.11
    - ip: 192.168.1.12
    ports:
    - port: 1
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: bm-fw
  labels:
    app: bm-fw
spec:
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
  sessionAffinity: None
  type: ClusterIP
    