apiVersion: batch/v1
kind: Job
metadata:
  name: data-extractor-job
  namespace: bm-fw
  labels:
    app: data-extractor-job
spec:
  parallelism: 1    
  completions: 1
  backoffLimit: 1
  template:         
    metadata:
      name: data-extractor-job
    spec:
      volumes:
      - name: data-extractor-scripts-volume
        configMap:
          name: data-extractor-scripts
      - name: job-storage
        glusterfs:
          endpoints: glusterfs-cluster
          path: gv_bm_fw/job
          readOnly: false
      containers:
      - name: data-extractor-job
        image: vookimedlo/ubuntu-gcc:gcc_eoan
        volumeMounts:
          - mountPath: /data-extractor-scripts
            name: data-extractor-scripts-volume
          - mountPath: /job-data
            name: job-storage
        command:
          - /bin/sh
          - /data-extractor-scripts/data-extractor-job.sh
        env:
          - name: INFLUXDB_HOST
            value: "data-extractor-influxdb"
          - name: INFLUXDB_PORT
            value: "8086"
          - name: INFLUXDB_DB
            value: "bmfw"
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "1000m"
      restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  data-extractor-scripts
  namespace: bm-fw
  labels:
    app: data-extractor-job
data:
    data-extractor-job.sh: |
      echo "--- Environment ---"
      env
      echo ""
      echo "--- Download libs ---"
      sudo apt-get update
      sudo apt-get install -y libyaml-dev zlib1g-dev
      cd /job-data
      if [ ! -d libxlsxwriter ]; then
        git clone https://github.com/jmcnamara/libxlsxwriter.git
      fi
      cd libxlsxwriter
      make
      sudo make install
      echo ""
      echo "--- Download Code ---"
      cd /job-data
      if [ ! -d BM_FW ]; then
        git clone https://github.com/danielvilas/BM_FW
        cd BM_FW
        git submodule init
        git submodule update
        cd ..
      fi
      cd BM_FW
      git pull
      cd DataExtractor
      echo ""
      echo "--- Building Code ---"
      mkdir -p build
      cd build
      cmake ..
      make
      cd ..
      echo ""
      echo "--- Cleaning Old Data ---"
      curl http://$INFLUXDB_HOST:$INFLUXDB_PORT/query -d q="DROP DATABASE ${INFLUXDB_DB}"
      curl http://$INFLUXDB_HOST:$INFLUXDB_PORT/query -d q="CREATE DATABASE ${INFLUXDB_DB}"
      echo ""
      echo "--- Printing Config ---"
      ./build/DataExporterInflux ../recorded_data_new/dataExtractor.yml 
      echo ""
      echo "--- Processing Data ---"
      ./build/DataExporterInflux ../recorded_data_new/dataExtractor.yml ../recorded_data_new/

      echo "done"
      
